name: Publish Libraries

on:
  release:
    types: [published]

jobs:
  publish-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build and publish
        run: |
          ./build.sh rust
          cd rust
          cargo publish --token ${{ secrets.CARGO_TOKEN }}

  publish-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build and publish
        run: |
          ./build.sh typescript
          cd typescript
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build and validate Go module
        run: |
          ./build.sh go
          cd go
          go mod tidy
          go test -v
      - name: Create and push Go module tag
        run: |
          # Extract version from GitHub release
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Publishing Go module version $VERSION"

          # The Go module will be available at the git tag
          # No additional publishing step needed - Go fetches from git tags
          echo "Go module will be available at: go get github.com/${{ github.repository }}/go@$VERSION"

